from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard_view, name='roster_home'),
    path('calendar/', views.home_calendar, name='roster_calendar'),
    path('daily/', views.roster_view, name='daily_roster'),
    path('statistics/', views.statistics_view, name='roster_stats'),
    path('lifecycle/', views.roster_lifecycle, name='roster_lifecycle'),
    path('export/<int:year>/<int:month>/', views.monthly_export_print, name='monthly_export_print'),
    path('leaves/weekend/', views.generate_weekend_leaves, name='generate_weekend_leaves'),
    path('leaves/daily/', views.daily_leave_manager, name='daily_leave_manager'),
    path('leaves/daily/print/<str:date_str>/', views.daily_leave_print, name='daily_leave_print'),
    path('batch-leave/save/', views.save_batch_leave, name='save_batch_leave'),
    path('soldier/<int:soldier_id>/', views.soldier_profile, name='soldier_profile'),
    path('swap/<int:shift_id>/', views.emergency_swap, name='emergency_swap'),
    path('debug/', views.debug_panel, name='debug_panel'),
    path('emergency-print/', views.emergency_list, name='emergency_print'),
    path('alert/post/', views.post_announcement, name='post_announcement'),
    path('alert/dismiss/', views.dismiss_announcement, name='dismiss_announcement'),
    path('swap-manager/', views.swap_manager, name='swap_manager'),
    path('api/login/', views.api_device_login, name='api_device_login'),
    path('api/my-shifts/', views.api_my_shifts, name='api_my_shifts'),
    path('api/announcements/', views.api_announcements, name='api_announcements'),
    path('api/announcements/ack/', views.api_acknowledge_alert, name='api_acknowledge_alert'),
    path('api/preferences/', views.api_submit_preference, name='api_submit_preference'),
    path('api/profile/', views.api_profile, name='api_profile'),
    path('api/daily-roster/', views.api_daily_roster, name='api_daily_roster'),
    path('api/marketplace/', views.api_market_list, name='api_market_list'),
    path('api/marketplace/put/', views.api_market_put, name='api_market_put'),
    path('api/marketplace/take/', views.api_market_take, name='api_market_take'),
]