# Generated by Django 6.0.1 on 2026-01-19 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOrRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Име на група/Курс')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет (за сортиране)')),
            ],
            options={
                'verbose_name': 'Курс/Група',
                'verbose_name_plural': 'Курсове и Групи',
            },
        ),
        migrations.CreateModel(
            name='DutyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Име на наряда')),
                ('people_required', models.IntegerField(default=1, verbose_name='Брой хора за смяна')),
                ('weight', models.IntegerField(default=1, verbose_name='Тежест (Точки)')),
                ('allowed_ranks', models.ManyToManyField(to='roster.courseorrank', verbose_name='Кой има право да го дава?')),
            ],
            options={
                'verbose_name': 'Вид Наряд',
                'verbose_name_plural': 'Видове Наряди',
            },
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Име')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('score', models.IntegerField(default=0, verbose_name='Натрупани точки (Наряди)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен (Не е уволнен)')),
                ('rank_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.courseorrank', verbose_name='Курс/Група')),
            ],
            options={
                'verbose_name': 'Военнослужещ',
                'verbose_name_plural': 'Военнослужещи',
            },
        ),
    ]
