# Generated by Django 6.0.1 on 2026-01-19 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата на раждане'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='class_section',
            field=models.CharField(blank=True, max_length=10, verbose_name='Класно отделение'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='company',
            field=models.CharField(choices=[('1', '1-ва Рота'), ('2', '2-ра Рота')], default='1', max_length=10, verbose_name='Рота'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='crew',
            field=models.CharField(blank=True, max_length=50, verbose_name='Екипаж'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='faculty_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Фак. номер'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='platoon',
            field=models.CharField(blank=True, max_length=10, verbose_name='Отряд/Взвод'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='rank_title',
            field=models.CharField(default='Курсант', help_text='Напр. Главен старшина', max_length=50, verbose_name='Звание (Текст)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='soldier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='rank_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.courseorrank', verbose_name='Курс/Група (За наряди)'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Натрупани точки'),
        ),
    ]
