# Generated by Django 6.0.1 on 2026-01-19 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_soldier_birth_date_soldier_class_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorrank',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='dutytype',
            name='allowed_ranks',
            field=models.ManyToManyField(to='roster.courseorrank'),
        ),
        migrations.AlterField(
            model_name='dutytype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dutytype',
            name='people_required',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dutytype',
            name='weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата на раждане (ДД.ММ.ГГГГ)'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='class_section',
            field=models.CharField(blank=True, help_text='Попълва се автоматично от Фак. номер', max_length=20, verbose_name='Класно отделение'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='company',
            field=models.CharField(choices=[('1', '1-ва Рота'), ('2', '2-ра Рота'), ('3', '3-та Рота'), ('Щаб', 'Щаб')], default='1', max_length=10, verbose_name='Рота'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='faculty_number',
            field=models.CharField(blank=True, help_text='Пример: 111-24112', max_length=20, null=True, unique=True, verbose_name='Фак. номер'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='platoon',
            field=models.CharField(choices=[('1', '1-ви взвод'), ('2', '2-ри взвод'), ('3', '3-ти взвод'), ('4', '4-ти взвод'), ('Млади', 'Млади курсанти')], default='1', max_length=20, verbose_name='Взвод/Отряд'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='rank_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.courseorrank', verbose_name='Курс (Басейн за наряди)'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='rank_title',
            field=models.CharField(choices=[('Курсант', 'Курсант (1-ви курс)'), ('Ст. II ст.', 'Старшина II степен'), ('Ст. I ст.', 'Старшина I степен'), ('Гл. старшина', 'Главен старшина'), ('Мичман', 'Мичман'), ('Оф. кандидат', 'Офицерски кандидат'), ('Лейтенант', 'Лейтенант'), ('Капитан', 'Капитан'), ('Майор', 'Майор'), ('Граждански', 'Гражданско лице')], default='Курсант', max_length=50, verbose_name='Звание'),
        ),
    ]
