# Generated by Django 6.0.1 on 2026-01-19 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_alter_courseorrank_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата на наряда')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създаден на')),
                ('duty_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.dutytype', verbose_name='Вид наряд')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.soldier', verbose_name='Назначен')),
            ],
            options={
                'verbose_name': 'Назначен наряд',
                'verbose_name_plural': 'График на нарядите',
                'unique_together': {('date', 'soldier')},
            },
        ),
    ]
