# Generated by Django 6.0.1 on 2026-01-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_dutyshift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='company',
            field=models.CharField(choices=[('1', '1-ва Рота'), ('2', '2-ра Рота'), ('Щаб', 'Щаб')], default='1', max_length=10, verbose_name='Рота'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='platoon',
            field=models.CharField(choices=[('1', '1-ви взвод'), ('2', '2-ри взвод'), ('3', '3-ти взвод'), ('4', '4-ти взвод'), ('Млади', 'Взвод млади курсанти')], default='1', max_length=20, verbose_name='Взвод/Отряд'),
        ),
    ]
