# Generated by Django 6.0.1 on 2026-01-21 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_alter_soldier_company_alter_soldier_platoon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начална дата')),
                ('end_date', models.DateField(verbose_name='Крайна дата')),
                ('leave_type', models.CharField(choices=[('home', 'Домашен отпуск'), ('sick', 'Болничен / Лазарет'), ('mission', 'Командировка'), ('arrest', 'Арест'), ('other', 'Друго')], default='home', max_length=20, verbose_name='Вид')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='Причина (опционално)')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.soldier', verbose_name='Военнослужещ')),
            ],
        ),
    ]
