# Generated by Django 5.2.11 on 2026-02-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='phone',
            field=models.CharField(blank=True, help_text='За оповестяване', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='courseorrank',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dutyshift',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dutytype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
