# Generated by Django 5.2.11 on 2026-02-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_soldier_phone_alter_courseorrank_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заглавие')),
                ('message', models.TextField(verbose_name='Съобщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Извънредно съобщение',
                'verbose_name_plural': 'Извънредни съобщения',
            },
        ),
    ]
