# Generated by Django 5.2.11 on 2026-02-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0008_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target',
            field=models.CharField(choices=[('all', '📢 ВСИЧКИ'), ('1', '⚓ 1-ва Рота'), ('2', '⚕️ 2-ра Рота'), ('young', '👶 Млади Курсанти'), ('staff', '⭐ Щаб / Офицери')], default='all', max_length=10, verbose_name='Получател'),
        ),
    ]
