# Generated by Django 5.2.11 on 2026-02-08 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0009_announcement_target'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soldier',
            options={},
        ),
    ]
