# Generated by Django 5.2.11 on 2026-02-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0010_alter_soldier_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='position',
            field=models.CharField(choices=[('Редови', 'Редови състав'), ('КО', 'Командир на отделение'), ('ЗКВ', 'Заместник командир на взвод'), ('КВД', 'Командир на взвод дубльор'), ('ЕК', 'Екипажен командир'), ('ЗЕК', 'Зам. екипажен командир'), ('ОК', 'Отряден командир'), ('ЗОК', 'Зам. отряден командир'), ('ДК', 'Дивизионен командир'), ('ЗДК', 'Зам. дивизионен командир'), ('КВ', 'Командир на взвод (Офицер)'), ('КР', 'Командир на рота (Офицер)'), ('КомБат', 'Командир на батальон (Офицер)')], default='Редови', max_length=15, verbose_name='Длъжност'),
        ),
    ]
