# Generated by Django 5.2.11 on 2026-02-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0011_soldier_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='company',
            field=models.CharField(choices=[('1', '1-ва Рота'), ('2', '2-ра Рота'), ('Млади', 'Млади курсанти'), ('Щаб', 'Щаб')], default='1', max_length=10, verbose_name='Рота'),
        ),
    ]
