# Generated by Django 5.2.11 on 2026-02-21 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0012_alter_soldier_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyshift',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Чернова'),
        ),
        migrations.CreateModel(
            name='ShiftPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('preference', models.CharField(choices=[('want', '🟩 Желая наряд (Доброволец)'), ('cannot', '🟥 Не мога (Блокиран ден)')], max_length=10, verbose_name='Тип желание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.soldier', verbose_name='Военнослужещ')),
            ],
            options={
                'verbose_name': 'Желание за наряд',
                'verbose_name_plural': 'Желания за наряди',
                'unique_together': {('soldier', 'date')},
            },
        ),
    ]
