# Generated by Django 5.2.11 on 2026-02-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0013_dutyshift_is_draft_shiftpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dutyshift',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='dutyshift',
            name='status',
            field=models.CharField(choices=[('admin_draft', '🔒 Скрита чернова'), ('public_draft', '👀 Проекто-наряд'), ('official', '✅ Утвърден')], default='admin_draft', max_length=20, verbose_name='Статус'),
        ),
    ]
