# Generated by Django 5.2.11 on 2026-02-23 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0015_soldier_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True, verbose_name='Хардуерно ID')),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name='Име на устройството')),
                ('public_key', models.TextField(blank=True, null=True, verbose_name='Биометричен публичен ключ')),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Последно IP')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Последна активност')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно/Разрешено')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.soldier', verbose_name='Военнослужещ')),
            ],
            options={
                'verbose_name': 'Оторизирано устройство',
                'verbose_name_plural': 'Оторизирани устройства',
            },
        ),
    ]
