# Generated by Django 5.2.11 on 2026-03-05 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0016_authorizeddevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='Основателна причина')),
                ('status', models.CharField(choices=[('open', '🟢 Търси заместник (На Борсата)'), ('waiting', '🟡 Има кандидат (Чака Капитана)'), ('approved', '✅ Одобрена'), ('rejected', '❌ Отхвърлена')], default='open', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='roster.soldier', verbose_name='Титуляр')),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='roster.dutyshift', verbose_name='Наряд')),
                ('substitute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_offers', to='roster.soldier', verbose_name='Кандидат-заместник')),
            ],
            options={
                'verbose_name': 'Заявка за смяна (Борса)',
                'verbose_name_plural': 'Борса за смени',
            },
        ),
    ]
