# Generated by Django 5.2.11 on 2026-03-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0017_shiftswaprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='has_scholarship',
            field=models.BooleanField(default=False, verbose_name='Получава стипендия'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateTimeField(verbose_name='Крайна дата'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateTimeField(verbose_name='Начална дата'),
        ),
    ]
