# Generated by Django 5.2.11 on 2026-03-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0018_soldier_has_scholarship_alter_leave_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('draft', '📝 Чернова'), ('official', '✅ Утвърдена')], default='official', max_length=20, verbose_name='Статус'),
        ),
    ]
