# Generated by Django 5.2.11 on 2026-03-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0020_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('city', 'Градска отпуска (ГО)'), ('home', 'Домашен отпуск'), ('sick', 'Болничен / Лазарет'), ('mission', 'Командировка'), ('arrest', 'Арест'), ('revoked', '🚫 Отказ от отпуска'), ('other', 'Друго')], default='city', max_length=20, verbose_name='Вид'),
        ),
    ]
