# Generated by Django 5.2.11 on 2026-03-25 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0021_alter_leave_leave_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('star', '⭐ Заслуга (Звездичка)'), ('dot', '⚫ Провинение (Черна точка)')], max_length=10, verbose_name='Тип')),
                ('reason', models.CharField(max_length=255, verbose_name='Причина')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_records', to='roster.soldier', verbose_name='Военнослужещ')),
            ],
            options={
                'verbose_name': 'Дисциплинарен запис',
                'verbose_name_plural': 'Дисциплинарен дневник',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
