# Generated by Django 5.2.11 on 2026-03-26 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0022_disciplinaryrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Извънредно съобщение', 'verbose_name_plural': 'Оповестяване'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='announcement_type',
            field=models.CharField(choices=[('alarm', '🚨 ТРЕВОГА'), ('fire', '🔥 ПОЖАР'), ('assembly', '📍 СБОР'), ('formation', '💂 СТРОЙ (Промяна/Преглед)'), ('mission', '✈️ КОМАНДИРОВКА'), ('volunteer', '🙋 ЗАЯВЯВАНЕ НА ЖЕЛАНИЕ'), ('info', 'ℹ️ ИНФОРМАЦИЯ')], default='info', max_length=20, verbose_name='Тип оповестяване'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Създадено на'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно (Изисква реакция)'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(verbose_name='Съобщение/Детайли'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target',
            field=models.CharField(choices=[('all', 'Целия батальон'), ('1', '1-ва рота'), ('2', '2-ра рота'), ('3', '3-та рота'), ('4', '4-та рота')], default='all', max_length=50, verbose_name='До кого'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='Важно съобщение', max_length=200, verbose_name='Заглавие/Тема'),
        ),
        migrations.CreateModel(
            name='AnnouncementReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочетено/Разбрано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Точен час на прочитане')),
                ('has_volunteered', models.BooleanField(blank=True, null=True, verbose_name='Записал се (Доброволец)')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='roster.announcement', verbose_name='Съобщение')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='roster.soldier', verbose_name='Военнослужещ')),
            ],
            options={
                'verbose_name': 'Разписка за оповестяване',
                'verbose_name_plural': 'Разписки',
                'unique_together': {('announcement', 'soldier')},
            },
        ),
    ]
